config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"
  get "product" => "pages#product"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def product
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "咕咚全球淘", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
     
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Product", product_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>
     <%= render "layouts/header" %>
     <div class="container">
     	<% flash.each do |name,msg| %>
           <%= content_tag(:div,msg, class: "alert-info") %>
      	<% end %>
         <%= yield %>
     </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>关于我们</h1>

<p>


	咕咚淘隶属于深圳启创讯科网络科技有限公司，是一家专门针对追求生活品质的人群创建的海淘网站，专营各种海外名品，以高质的产品和服务为用户提供更加有品质的生活。 我们拥有几十家供应商、近百个国外品牌、超过万件商品，可以让您享受更为便捷、快速、安全和实惠的海外购物体验。 咕咚淘提供的商品与国外价格保持一致，汇率实时更新，支持人民币支付，可以用支付宝哦！。 我们为您选择更为快速和安全的物流服务，我们的宗旨是让您的海外购物不再是难事！ 
</p>
</br>
</br>
</br>
</br>
</br>

<div class="media">
  <a class="media-left" href="#">
    <img src="http://beilou-photos.b0.upaiyun.com/products/15/c0/3b/15c03b59-80dd-4417-8493-53212972fbca!596x596" alt="...">
  </a>
  <div class="media-body">
    <h4 class="media-heading">创始人</h4>
    创始人  刘小胖
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>小胖带你购遍美利坚</h1>
  <% if user_signed_in? %>
  # do something
  <% else %>
    <p>
      <%= link_to "Log in", new_user_session_path ,class: "btn btn-primary btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
 <% end %>
</div>


<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      
      <img src="http://beilou-photos.b0.upaiyun.com/details/f8/99/2f/f8992f94-77a5-49b1-82b1-522149e82238"/>
      <div class="caption">
        <h3>拉尔夫·劳伦卫衣</h3>
        <p>
</br>
【品牌介绍】：拉尔夫·劳伦(RALPH LAUREN)是时装界的“美国经典”。拉尔夫·劳伦是有着浓浓美国气息的高品味时装品牌，款式高度风格化。除时装外，拉夫·劳伦（Ralph Lauren）品牌还包括香水、童装、家居等产品。无论是服装还是家具，无论是香水还是器皿，都迎合了顾客对上层社会完美生活的向往。或者正如Ralph Lauren（拉夫·劳伦 ）先生本人所说：“我设计的目的就是去实现人们心目中的美梦——可以想象到的最好现实。” 
</br>
【商品中文】：RALPH LAUREN 拉尔夫·劳伦 女款修身休闲裤 裤脚拉链 侧兜设计 蓝色 
        </p>
        <p>
        	<a href="https://d2i5khuir6rc3s.cloudfront.net/media/user_profile_pic/87a59f0b-1082-4a03-8d86-9a64eb72bd75.jpg" class="btn btn-primary" role="button">查看</a>
        </p>

      </div>
    </div>






<div class="content-container" id="fashionista">
    <div class="section">
        <h2>START SHOPPING</h2>
       
        <p class="sub-header">Let our stylists show you how they make it work.</p>
        <div class="listing">

<table border="1">
<tr>
<th>Heading</th>
<th>Another Heading</th>
</tr>
<tr>
<td>
	<a href="/fashionistas/mengsb/">
    <div class="stylist">
        <div class="stylist-img"><img src="https://d2i5khuir6rc3s.cloudfront.net/media/user_profile_pic/d9760471-20b3-4012-bdf2-624a50d3f5ba.jpg" class="img-responsive"/></div>
        <div class="info">
            <h3>Mengshi</h3>
            
            <p class="stylist-text">L.A, CA</p>
            
            <p class="stylist-tagline">Style: because personality isn&#39;t the first thing people see.</p>
        </div>
    </div>
</a> 

</td>
<td>
	 <a href="/fashionistas/mengsb/">
    <div class="stylist">
        <div class="stylist-img"><img src="https://d2i5khuir6rc3s.cloudfront.net/media/user_profile_pic/d9760471-20b3-4012-bdf2-624a50d3f5ba.jpg" class="img-responsive"/></div>
        <div class="info">
            <h3>Mengshi</h3>
            
            <p class="stylist-text">L.A, CA</p>
            
            <p class="stylist-tagline">Style: because personality isn&#39;t the first thing people see.</p>
        </div>
    </div>
</a>  

</td>
</tr>
<tr>
<td>
    <a href="/fashionistas/fengwan/">
    <div class="stylist">
        <div class="stylist-img"><img src="https://d2i5khuir6rc3s.cloudfront.net/media/user_profile_pic/9b0ca770-acd7-4c05-a523-5d22eeb0273d.jpg" class="img-responsive"/></div>
        <div class="info">
            <h3>Fengwan</h3>
            
            <p class="stylist-text">L.A, CA</p>
            
            <p class="stylist-tagline">I am willing to try anything. My favorite style is effortless, edgy and fresh. </p>
        </div>
    </div>
</a>
</td>
<td>
	<a href="/fashionistas/mengsb/">
    <div class="stylist">
        <div class="stylist-img"><img src="https://d2i5khuir6rc3s.cloudfront.net/media/user_profile_pic/d9760471-20b3-4012-bdf2-624a50d3f5ba.jpg" class="img-responsive"/></div>
        <div class="info">
            <h3>Mengshi</h3>
            
            <p class="stylist-text">L.A, CA</p>
            
            <p class="stylist-tagline">Style: because personality isn&#39;t the first thing people see.</p>
        </div>
    </div>
    </a>

</td>
</tr>
</table>









            
                
                    


                
         
                
                   
  


  </div>
</div>

app/views/pages/product.html.erb
<div class="jumbotron center">
  <h2>来一次省一年！足不出户血拼美国</h2>
  <p>
     <%= link_to "立即下单", "#" ,class: "btn btn-primary btn-lg" %>
     <%= link_to "寻找现货","#", class: "btn btn-primary btn-lg" %>
  </p>



</div>


<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    品类选择
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">美国名牌鞋类</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">高级服饰</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">运动鞋</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">奶粉婴幼儿产品</a></li>
  </ul>
</div>


<p>
</br>
</br>
蜜淘承诺所售商品均为海外购买的正品行货。如客户在蜜淘购买的商品确认收货后发现不是正品， 应将质检部门出具的鉴定证明连同商品原件寄至我们，核实并认定属实后，我们将无条件"假一赔十"。
</p>

<p>
一、代购服务细则
</br>【全球精选，正品同步】
所有代购商品均为美国、日本、韩国等海外当地知名网站正在销售中的新款或经典商品，由咕咚网时尚买手、母婴专家或者新老用户推荐、筛选最终同步到蜜淘网销售。
</br>【一键代购，方便快捷】
您在网下单后，我们会在72小时内到国外网站代为您下单购买，再通过国际快递将商品送到您手中，省去您翻译网站、联系转运的繁琐。
</br>【便捷支付，费用透明】
您可以根据自身情况使用银联卡或支付宝用人民币结算，您支付的金额包含了商品价格和国际国内运费，不包含税费。
如果产生了税费，需要您自行向海关缴纳（方式方法具体见FAQ）。 
此外，海外代购商品由于国外政策限制，无法提供发票。
</br>【海外直邮，安全无忧】
所有代购商品均为海外直邮，韩国和日本代购商品直发EMS到用户手中，美国代购商品通过转运公司在天津口岸清关后转国内快递送达用户手中。
海外代购（下单——付款——海外订购——海外仓库中转——国际航空运输——国内清关——国内派送）周期在15天-30天，由于涉及国际运输和国外仓库节假日休息，如果遇到恶劣天气或者节假日，到货时间会相应顺延。
</p>


<p>
</br>二、20天物流承诺
</br>我们承诺20个工作日内发出国内物流单号，即：以客户端内显示的物流状态为参考，自下单日起到国内快递发出期间不超过20个工作日，超过20个工作日蜜淘承诺</br>免除国际运费。但如果产生关税，因需您自主进行缴纳关税，故处理关税的时间不计算在内。
</br>20天承诺不包括部分海外商家可能发生延迟发货的行为，如果发生这种情况蜜淘会协助沟通催促尽快发货。
</br>我们与笨鸟物流在海外及国内建立可靠合作关系，保证商品中转运输过程中的包裹完整、安全及隐私。
</br>我们与国内快递达成合作关系，国内运送时间具体参看国内快递公司的效率，不包含在蜜淘承诺周期之内。

</br>三、有关缺货、取消订单及退换货的说明
</br>（一）、缺货、取消订单需知
</br>由于海外网站的库存是实时更新的，我们在代为您下单时如果出现了缺货的情况，系统会在5个工作日内将您支付的金额全额返还到您的支付账户。
</br>在您下单后到被蜜淘进行处理之前，如果您发现订单有误，可以在客户端上对您的订单进行取消订单操作。
</br>当您的订单被蜜淘处理进行处理之后(蜜淘客户端订单的物流状态中将会显示`「订单已处理」`)，将不支持取消订单的操作。
</br>（二）、商品在输送过程中发生破损、缺失及丢失等质量问题的，经协商且用户同意后，换货范围如下。
</br>受理的范围包括：
</br>到手商品发生破损、缺失等质量问题，影响正常使用。
</br>到手商品质保过期（主要为食品及药妆类）。
</br>快递公司将商品丢失。
</br>出现以上情况时，您可以在收到货物后的7天内申请退换货，退货时请将商品包括附带的全部资料/配件予以退回，退换货中产生的运费由我们承担。
</p>